routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['uses' => 'HomeController']);

Route::group(['prefix' => 'crud', 'namespace' => 'CRUD', 'as' => 'crud.'], function () {
    Route::resource('users', 'UserController', ['except' => 'show']);
    Route::resource('user-groups', 'UserGroupController', ['except' => 'show']);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class User
 * @package App\Models
 * @property int $id
 * @property string $first_name
 * @property string $last_name
 * @property string $phone
 * @property string $email
 * @property Carbon\Carbon $created_at
 * @property Carbon\Carbon $updated_at
 */
class User extends Model
{
    protected $guarded = ['id'];

    protected $appends = ['groupName', 'editUrl', 'deleteUrl'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function group()
    {
        return $this->belongsTo(UserGroup::class, 'user_group_id', 'id');
    }

    /**
     * @return string
     */
    public function getGroupNameAttribute()
    {
        return $this->group->name;
    }

    /**
     * @return string
     */
    public function getEditUrlAttribute()
    {
        return route('crud.users.edit', ['user' => $this->id]);
    }

    /**
     * @return string
     */
    public function getDeleteUrlAttribute()
    {
        return route('crud.users.destroy', ['user' => $this->id]);
    }
}

app/Models/UserGroup.php
<?php

namespace App\Models;

use App\Enums\RoleEnum;
use Illuminate\Database\Eloquent\Model;

/**
 * Class UserGroup
 * @package App\Models
 * @property int $id
 * @property string $name
 * @property string $description
 * @property string $role
 * @property Carbon\Carbon $created_at
 * @property Carbon\Carbon $updated_at
 */
class UserGroup extends Model
{
    protected $guarded = ['id'];

    protected $appends = ['roleName', 'editUrl', 'deleteUrl'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function users()
    {
        return $this->hasMany('users');
    }

    /**
     * @return array
     */
    public static function getSelectData()
    {
        $selectOptions = [];
        $items = self::get();
        $items->each(function ($item) use (&$selectOptions) {
            $selectOptions[$item->id] = $item->name;
        });
        return $selectOptions;
    }

    /**
     * @return string
     */
    public function getRoleNameAttribute()
    {
        return RoleEnum::label($this->role);
    }

    /**
     * @return string
     */
    public function getEditUrlAttribute()
    {
        return route('crud.user-groups.edit', ['user_group' => $this->id]);
    }

    /**
     * @return string
     */
    public function getDeleteUrlAttribute()
    {
        return route('crud.user-groups.destroy', ['user_group' => $this->id]);
    }
}

app/Http/Controllers/CRUD/UserController.php
<?php

namespace App\Http\Controllers\CRUD;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreUserRequest;
use App\Models\User;
use App\Models\UserGroup;

class UserController extends Controller
{
    public function index()
    {
        $users = User::with('group')->get();

        return view('crud.users.index', compact('users'));
    }

    public function create()
    {
        return view('crud.users.create', [
            'groupsSelectData' => UserGroup::getSelectData()
        ]);
    }

    public function store(StoreUserRequest $request)
    {
        User::create($request->only('first_name', 'last_name', 'phone', 'email', 'user_group_id'));

        return redirect()
            ->route('crud.users.index');
    }

    public function edit($id)
    {
        return view('crud.users.edit', [
            'user' => User::find($id),
            'groupsSelectData' => UserGroup::getSelectData()
        ]);
    }

    public function update(StoreUserRequest $request, $id)
    {
        User::findOrFail($id)->update($request->only('first_name', 'last_name', 'phone', 'email', 'user_group_id'));

        return redirect()
            ->route('crud.users.index');
    }

    public function destroy($id)
    {
        User::find($id)->delete();
    }
}

app/Http/Controllers/CRUD/UserGroupController.php
<?php

namespace App\Http\Controllers\CRUD;

use App\Enums\RoleEnum;
use App\Http\Controllers\Controller;
use App\Models\UserGroup;
use App\Http\Requests\StoreUserGroupRequest;

class UserGroupController extends Controller
{
    public function index()
    {
        $userGroups = UserGroup::get();

        return view('crud.user_groups.index', compact('userGroups'));
    }

    public function create()
    {
        return view('crud.user_groups.create', [
            'rolesSelectData' => RoleEnum::labels()
        ]);
    }

    public function store(StoreUserGroupRequest $request)
    {
        UserGroup::create($request->only('name', 'description', 'role'));

        return redirect()
            ->route('crud.user-groups.index');
    }

    public function edit($id)
    {
        return view('crud.user_groups.edit', [
            'userGroup' => UserGroup::find($id),
            'rolesSelectData' => RoleEnum::labels()
        ]);
    }

    public function update(StoreUserGroupRequest $request, $id)
    {
        UserGroup::findOrFail($id)->update($request->only('name', 'description', 'role'));

        return redirect()
            ->route('crud.user-groups.index');
    }

    public function destroy($id)
    {
        UserGroup::find($id)->delete();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php
namespace App\Http\Controllers;

use App\Models\User;
use App\Models\UserGroup;

class HomeController extends Controller
{
    public function __invoke()
    {
        $usersCount = User::count();
        $groupsCount = UserGroup::count();

        return view('home', compact('usersCount', 'groupsCount'));
    }
}

resources/views/crud/user_groups/create.blade.php
@extends('layouts.master')

@section('title') Create user group @endsection

@section('content')
    <div id="app">
        <h1 class="page-header text-center">
            <i class="fa fa-pencil"></i> Create user group
        </h1>
        <div class="row">
            @if (count($errors) > 0)
                @include('layouts.partials.validation_errors')
            @endif
            {{ Form::open(['url' => route('crud.user-groups.store')]) }}
            <div class="form-group">
                <label for="name">Name</label>
                {{ Form::text('name', old('name'), ['class' => 'form-control']) }}
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                {{ Form::text('description', old('description'), ['class' => 'form-control']) }}
            </div>
            <div class="form-group">
                <label for="role">Role</label>
                {{ Form::select('role', $rolesSelectData, null, ['class' => 'form-control']) }}
            </div>
            <div class="button-group">
                <a href="{{ route('crud.user-groups.index') }}" class="btn btn-default">
                    <i class="fa fa-arrow-left"></i> Back
                </a>
                {{ Form::submit('Save', ['class' => 'btn btn-success']) }}
            </div>
            {{ Form::close() }}

        </div>
    </div>
@endsection

resources/views/crud/user_groups/edit.blade.php
@extends('layouts.master')

@section('title') Edit user group @endsection

@section('content')
    <div id="app">
        <h1 class="page-header text-center">
            <i class="fa fa-pencil"></i> Edit user group #{{ $userGroup->id }}
        </h1>
        <div class="row">
            @if (count($errors) > 0)
                @include('layouts.partials.validation_errors')
            @endif
            {{ Form::open(['url' => route('crud.user-groups.update', ['user_group' => $userGroup->id]), 'method' => 'put']) }}
                <div class="form-group">
                    <label for="name">Name</label>
                    {{ Form::text('name', old('name') ?? $userGroup->name, ['class' => 'form-control']) }}
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    {{ Form::text('description', old('description') ?? $userGroup->description, ['class' => 'form-control']) }}
                </div>
                <div class="form-group">
                    <label for="role">Role</label>
                    {{ Form::select('role', $rolesSelectData, $userGroup->role, ['class' => 'form-control']) }}
                </div>
                <div class="button-group">
                    <a href="{{ route('crud.user-groups.index') }}" class="btn btn-default">
                        <i class="fa fa-arrow-left"></i> Back
                    </a>
                    {{ Form::submit('Save', ['class' => 'btn btn-success']) }}
                </div>
            {{ Form::close() }}

        </div>
    </div>
@endsection

resources/views/crud/user_groups/index.blade.php
@extends('layouts.master')

@section('title') User Groups @endsection

@section('content')
    <div id="app">
        <h1 class="page-header text-center">
            <i class="fa fa-users"></i> User Groups
        </h1>
        <div class="row">
            <div class="col-xs-6">
                <div class="btn-group">
                    <a href="{{ route('crud.user-groups.create') }}" class="btn btn-primary">
                        <i class="fa fa-plus"></i> Create New
                    </a>
                </div>
            </div>
            <div class="col-xs-6">
                <input v-model="query" type="text" class="form-control" placeholder="Search...">
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-for="column in columns" v-on:click="sortBy(column.propertyName)" style="cursor: pointer">
                        @{{ column.displayName }}
                        <i v-if="sortKey == column.propertyName" v-bind:class="'fa '+[sortDirection == 'asc' ? 'fa-chevron-up' : 'fa-chevron-down']"></i>
                    </th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="item in filter(items)">
                    <td v-for="column in columns">
                        @{{ item[column.propertyName] }}
                    </td>
                    <td>
                        <a v-bind:href="item.editUrl" class="btn btn-success">
                            <i class="fa fa-pencil"></i>
                        </a>
                        <a v-on:click.prevent="removeItem(item)" href="#" class="btn btn-danger">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('footer_scripts')
    <script>
        var appConfigs = {
            columns: [
                {propertyName: 'id', displayName: '#'},
                {propertyName: 'name', displayName: 'Name'},
                {propertyName: 'roleName', displayName: 'Role'}
            ],
            items: JSON.parse('{!! $userGroups->toJson() !!}')
        };
    </script>
    <script src="{{ asset('js/app.js') }}"></script>
@endsection

resources/views/crud/users/create.blade.php
@extends('layouts.master')

@section('title') Create user @endsection

@section('content')
    <div id="app">
        <h1 class="page-header text-center">
            <i class="fa fa-pencil"></i> Create user
        </h1>
        <div class="row">
            @if (count($errors) > 0)
                @include('layouts.partials.validation_errors')
            @endif
            {{ Form::open(['url' => route('crud.users.store')]) }}
                <div class="form-group">
                    <label for="first_name">First name</label>
                    {{ Form::text('first_name', old('first_name'), ['class' => 'form-control']) }}
                </div>
                <div class="form-group">
                    <label for="last_name">Last name</label>
                    {{ Form::text('last_name', old('last_name'), ['class' => 'form-control']) }}
                </div>
                <div class="form-group">
                    <label for="phone">Phone</label>
                    {{ Form::text('phone', old('phone'), ['class' => 'form-control']) }}
                </div>
                <div class="form-group">
                    <label for="first_name">Email</label>
                    {{ Form::email('email', old('email'), ['class' => 'form-control']) }}
                </div>
                <div class="form-group">
                    <label for="user_group_id">User group</label>
                    {{ Form::select('user_group_id', $groupsSelectData, null, ['class' => 'form-control']) }}
                </div>
                <div class="button-group">
                    <a href="{{ route('crud.users.index') }}" class="btn btn-default">
                        <i class="fa fa-arrow-left"></i> Back
                    </a>
                    {{ Form::submit('Save', ['class' => 'btn btn-success']) }}
                </div>
            {{ Form::close() }}

        </div>
    </div>
@endsection

resources/views/crud/users/edit.blade.php
@extends('layouts.master')

@section('title') Edit user @endsection

@section('content')
    <div id="app">
        <h1 class="page-header text-center">
            <i class="fa fa-pencil"></i> Edit user #{{ $user->id }}
        </h1>
        <div class="row">
            @if (count($errors) > 0)
                @include('layouts.partials.validation_errors')
            @endif
            {{ Form::open(['url' => route('crud.users.update', ['user' => $user->id]), 'method' => 'put']) }}
                <div class="form-group">
                    <label for="first_name">First name</label>
                    {{ Form::text('first_name', old('first_name') ?? $user->first_name, ['class' => 'form-control']) }}
                </div>
                <div class="form-group">
                    <label for="last_name">Last name</label>
                    {{ Form::text('last_name', old('last_name') ?? $user->last_name, ['class' => 'form-control']) }}
                </div>
                <div class="form-group">
                    <label for="phone">Phone</label>
                    {{ Form::text('phone', old('phone') ?? $user->phone, ['class' => 'form-control']) }}
                </div>
                <div class="form-group">
                    <label for="first_name">Email</label>
                    {{ Form::email('email', old('email') ?? $user->email, ['class' => 'form-control']) }}
                </div>
                <div class="form-group">
                    <label for="user_group_id">User group</label>
                    {{ Form::select('user_group_id', $groupsSelectData, $user->user_group_id, ['class' => 'form-control']) }}
                </div>
                <div class="button-group">
                    <a href="{{ route('crud.users.index') }}" class="btn btn-default">
                        <i class="fa fa-arrow-left"></i> Back
                    </a>
                    {{ Form::submit('Save', ['class' => 'btn btn-success']) }}
                </div>
            {{ Form::close() }}

        </div>
    </div>
@endsection

resources/views/crud/users/index.blade.php
@extends('layouts.master')

@section('title') Users @endsection

@section('content')
    <div id="app">
        <h1 class="page-header text-center">
            <i class="fa fa-address-book"></i> Users
        </h1>
        <div class="row">
            <div class="col-xs-6">
                <div class="btn-group">
                    <a href="{{ route('crud.users.create') }}" class="btn btn-primary">
                        <i class="fa fa-plus"></i> Create New
                    </a>
                </div>
            </div>
            <div class="col-xs-6">
                <input v-model="query" type="text" class="form-control" placeholder="Search...">
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-for="column in columns" v-on:click="sortBy(column.propertyName)" style="cursor: pointer">
                        @{{ column.displayName }}
                        <i v-if="sortKey == column.propertyName" v-bind:class="'fa '+[sortDirection == 'asc' ? 'fa-chevron-up' : 'fa-chevron-down']"></i>
                    </th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="item in filter(items)">
                    <td v-for="column in columns">
                        @{{ item[column.propertyName] }}
                    </td>
                    <td>
                        <a v-bind:href="item.editUrl" class="btn btn-success">
                            <i class="fa fa-pencil"></i>
                        </a>
                        <a v-on:click.prevent="removeItem(item)" href="#" class="btn btn-danger">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('footer_scripts')
    <script>
        var appConfigs = {
            columns: [
                {propertyName: 'id', displayName: '#'},
                {propertyName: 'first_name', displayName: 'First Name'},
                {propertyName: 'last_name', displayName: 'Last Name'},
                {propertyName: 'groupName', displayName: 'Group Name'},
                {propertyName: 'phone', displayName: 'Phone'},
                {propertyName: 'email', displayName: 'Email'}
            ],
            items: JSON.parse('{!! $users->toJson() !!}')
        };
    </script>
    <script src="{{ asset('js/app.js') }}"></script>
@endsection

resources/views/home.blade.php
@extends('layouts.master')

@section('title') User Management @endsection

@section('content')
    <h1 class="page-header text-center">User Management</h1>
    <div class="row placeholders">
        <div class="col-xs-6 placeholder">
            <a href="{{ route('crud.users.index') }}">
                <i class="fa fa-address-card fa-5x"></i>
                <h4>Users</h4>
                <span class="text-muted">{{ $usersCount }}</span>
            </a>
        </div>
        <div class="col-xs-6 placeholder">
            <a href="{{ route('crud.user-groups.index') }}">
                <i class="fa fa-users fa-5x"></i>
                <h4>User Groups</h4>
                <span class="text-muted">{{ $groupsCount }}</span>
            </a>
        </div>
    </div>
@stop

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="_token" content="{{ csrf_token() }}">
    <title>@yield('title')</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://getbootstrap.com/examples/dashboard/dashboard.css">
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">User Management</a>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li @if(Route::current()->getName() === 'crud.users.index') class="active" @endif>
                    <a href="{{ route('crud.users.index') }}">
                        <i class="fa fa-address-book"></i> Users
                    </a>
                </li>
                <li @if(Route::current()->getName() === 'crud.user-groups.index') class="active" @endif>
                    <a href="{{ route('crud.user-groups.index') }}">
                        <i class="fa fa-users"></i> User Groups
                    </a>
                </li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            @yield('content')
        </div>
    </div>
</div>

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/vue/2.1.5/vue.min.js"></script>
@yield('footer_scripts')
</body>
</html>

resources/views/layouts/partials/validation_errors.blade.php
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>